# lab: lab-shell.cpp lab-shell-task1.h lab-shell-task1.cpp lab-shell-task2.h lab-shell-task2.cpp lab-shell-utils.h
g++ lab-shell.cpp lab-shell-task1.h lab-shell-task1.cpp lab-shell-task2.h lab-shell-task2.cpp lab-shell-utils.h -o lab -std=c++11 -Wall
